# Generated by Django 5.1 on 2024-08-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_contact_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='new',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
